[package]
name = "leptos-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.6"
leptos_router = "0.6"
leptos_meta = "0.6"
console_error_panic_hook = "0.1"
log = "0.4"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[build-dependencies]
